import { Router } from 'express'
import type { Request, Response } from 'express'
import multer from 'multer'
import { existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { randomUUID, createHash } from 'node:crypto'
import { getPostgresSql } from '../database/client.js'
import { requireWorkspaceId } from '../auth/workspace.js'
import { WORKSPACE_APPLICATION_MATERIALS_DIR } from '../data-paths.js'
import { inspectImage } from '../application-materials.js'
import { AiError, completeStructured, isAiTaskEnabled, loadArkConfig, resolveAiTask, type ChatContent } from '../ai.js'
import { loadPrompt } from '../prompt-loader.js'
import { resolveAppliedDate } from '../application-dates.js'
import { EXTRACTION_SCHEMA, IMPORT_LIMITS, IMPORT_FIELDS, normalizeExtraction, validateExtraction, type ImportDraft, type ImportSource, type ImportAnalysis } from '../../../shared/application-import.js'

export const cloudApplicationImportsRouter = Router()
const upload = multer({ storage: multer.memoryStorage(), limits: { files: IMPORT_LIMITS.images * 2, fileSize: IMPORT_LIMITS.imageBytes, fieldSize: IMPORT_LIMITS.text * 4 + 2000 } }).fields([{ name: 'images', maxCount: IMPORT_LIMITS.images }, { name: 'inference_images', maxCount: IMPORT_LIMITS.images }])
mkdirSync(WORKSPACE_APPLICATION_MATERIALS_DIR, { recursive: true })
class CloudImportError extends Error { constructor(message: string, readonly status = 422) { super(message) } }
function materialPath(workspaceId: string, name: string): string { return path.join(WORKSPACE_APPLICATION_MATERIALS_DIR, workspaceId, path.basename(name)) }
function safeName(name: string): string { const bytes = Buffer.from(name, 'latin1'); const decoded = bytes.toString('utf8'); return path.basename(decoded !== name && Buffer.from(decoded, 'utf8').equals(bytes) ? decoded : name).slice(0, 200) }
function captured(value: unknown): string | null { if (value == null || value === '') return null; if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value)) throw new CloudImportError('材料截取日期格式不正确'); return value }
async function draft(workspaceId: string, id: string): Promise<ImportDraft> {
  const sql = getPostgresSql(); const rows = await sql.unsafe('SELECT * FROM application_imports WHERE workspace_id=$1 AND id=$2', [workspaceId, id]) as Array<{ application_id: number | null; analysis_json: string | null; expires_at: string }>
  const row = rows[0]; if (!row) throw new CloudImportError('材料不存在或已清理，请重新上传', 404); if (!row.application_id && new Date(row.expires_at).getTime() <= Date.now()) throw new CloudImportError('临时材料已过期，请重新上传', 410)
  const sources = await sql.unsafe('SELECT * FROM application_materials WHERE workspace_id=$1 AND import_id=$2 ORDER BY id', [workspaceId, id]) as Array<Record<string, unknown>>
  return { id, application_id: row.application_id, analysis: row.analysis_json ? JSON.parse(row.analysis_json) as ImportAnalysis : null, sources: sources.map(source => ({ id: String(source.id), kind: source.kind as 'text' | 'image', text: source.text_content as string | null, filename: source.filename as string | null, mime: source.mime as string | null, captured_at: source.captured_at as string | null, url: source.stored_name ? `/api/application-imports/${id}/sources/${source.id}/file` : null })) }
}
function config() { const cfg = loadArkConfig(); const resolved = resolveAiTask('applicationImport'); const image = resolved?.modelEntry.vision ? resolved.modelEntry : cfg?.models.find(model => model.vision); return { available: !!cfg && isAiTaskEnabled('applicationImport') && !!resolved, model: resolved?.model ?? null, imageModel: image?.id ?? null, maxImages: Math.min(IMPORT_LIMITS.images, resolved?.maxImages ?? IMPORT_LIMITS.images) } }

cloudApplicationImportsRouter.get('/config', (_req, res) => res.json(config()))
cloudApplicationImportsRouter.post('/', (req, res, next) => upload(req, res, error => { if (error) return res.status(422).json({ message: '上传失败：仅支持最多 9 张、每张不超过 10 MB 的图片，文字最多 20000 字' }); void create(req, res).catch(next) }))
async function create(req: Request, res: Response): Promise<void> {
  const workspaceId = requireWorkspaceId(req); const text = typeof req.body?.text === 'string' ? req.body.text.trim() : ''; const files = ((req.files ?? {}) as Record<string, Express.Multer.File[]>).images ?? []; const inference = ((req.files ?? {}) as Record<string, Express.Multer.File[]>).inference_images ?? []
  if (!text && !files.length) throw new CloudImportError('请添加文字或截图'); if (text.length > IMPORT_LIMITS.text || files.length > IMPORT_LIMITS.images || files.length !== inference.length || files.reduce((n, f) => n + f.size, 0) > IMPORT_LIMITS.totalBytes) throw new CloudImportError('材料数量或大小超限')
  let meta: { text_date?: unknown; image_dates?: unknown }; try { meta = JSON.parse(req.body?.metadata ?? '{}') } catch { throw new CloudImportError('材料信息格式不正确') }
  const dates = meta.image_dates ?? files.map(() => null); if (!Array.isArray(dates) || dates.length !== files.length) throw new CloudImportError('截图日期必须与图片一一对应')
  const id = randomUUID(); const directory = path.join(WORKSPACE_APPLICATION_MATERIALS_DIR, workspaceId); mkdirSync(directory, { recursive: true }); const names: string[] = []
  try {
    await getPostgresSql().begin(async tx => {
      await tx.unsafe('INSERT INTO application_imports (id,workspace_id,expires_at) VALUES ($1,$2,now()+interval \'24 hours\')', [id, workspaceId])
      if (text) await tx.unsafe('INSERT INTO application_materials (id,import_id,workspace_id,kind,text_content,captured_at) VALUES ($1,$2,$3,\'text\',$4,$5)', ['text_1', id, workspaceId, text, captured(meta.text_date)])
      for (let index = 0; index < files.length; index++) { const original = inspectImage(files[index].buffer); const copy = inspectImage(inference[index].buffer); if (Math.max(copy.width, copy.height) > 2048) throw new CloudImportError('图片推理副本最长边不能超过 2048 像素'); const name = `${randomUUID()}.${original.ext}`; const inferenceName = `${randomUUID()}.${copy.ext}`; writeFileSync(materialPath(workspaceId, name), files[index].buffer, { flag: 'wx' }); writeFileSync(materialPath(workspaceId, inferenceName), inference[index].buffer, { flag: 'wx' }); names.push(name, inferenceName); await tx.unsafe('INSERT INTO application_materials (id,import_id,workspace_id,kind,filename,stored_name,mime,captured_at,inference_stored_name,inference_mime) VALUES ($1,$2,$3,\'image\',$4,$5,$6,$7,$8,$9)', [`image_${index + 1}`, id, workspaceId, safeName(files[index].originalname), name, original.mime, captured(dates[index]), inferenceName, copy.mime]) }
    })
  } catch (error) { names.forEach(name => { try { unlinkSync(materialPath(workspaceId, name)) } catch {} }); throw error }
  res.status(201).json(await draft(workspaceId, id))
}
cloudApplicationImportsRouter.get('/:id', async (req, res, next) => { try { res.json(await draft(requireWorkspaceId(req), req.params.id)) } catch (error) { next(error) } })
cloudApplicationImportsRouter.get('/:id/sources/:sourceId/file', async (req, res, next) => { try { const workspaceId = requireWorkspaceId(req); await draft(workspaceId, req.params.id); const rows = await getPostgresSql().unsafe('SELECT stored_name,mime FROM application_materials WHERE workspace_id=$1 AND import_id=$2 AND id=$3', [workspaceId, req.params.id, req.params.sourceId]) as Array<{ stored_name: string; mime: string }>; if (!rows[0] || !existsSync(materialPath(workspaceId, rows[0].stored_name))) throw new CloudImportError('图片不存在', 404); res.setHeader('X-Content-Type-Options', 'nosniff'); res.type(rows[0].mime).sendFile(materialPath(workspaceId, rows[0].stored_name)) } catch (error) { next(error) } })
cloudApplicationImportsRouter.post('/:id/analyze', async (req, res, next) => { try { const workspaceId = requireWorkspaceId(req); const source = await draft(workspaceId, req.params.id); if (source.application_id) throw new CloudImportError('已保存的材料不能重新识别', 409); const capabilities = config(); const images = source.sources.filter(item => item.kind === 'image'); const model = images.length ? capabilities.imageModel : capabilities.model; if (!model) throw new CloudImportError(images.length ? '请在 config.json 配置 vision: true 的图片模型' : '尚未配置可用 AI 模型'); const content: Exclude<ChatContent, string> = [{ type: 'text', text: JSON.stringify({ task: '提取一个岗位，材料如下', sources: source.sources.map(item => ({ id: item.id, captured_at: item.captured_at })) }) }]; for (const item of source.sources) { content.push({ type: 'text', text: JSON.stringify({ source_id: item.id, material_text: item.text }) }); if (item.kind === 'image') { const row = await getPostgresSql().unsafe('SELECT inference_stored_name,inference_mime FROM application_materials WHERE workspace_id=$1 AND import_id=$2 AND id=$3', [workspaceId, source.id, item.id]) as Array<{ inference_stored_name: string; inference_mime: string }>; content.push({ type: 'image_url', image_url: { url: `data:${row[0].inference_mime};base64,${readFileSync(materialPath(workspaceId, row[0].inference_stored_name)).toString('base64')}` } }) } } content.push({ type: 'text', text: '材料已提供完毕。请按系统规则输出 JSON。' }); const prompt = loadPrompt('application-extract.system.md'); const result = await completeStructured([{ role: 'system', content: `${prompt}\n\nJSON Schema:\n${JSON.stringify(EXTRACTION_SCHEMA)}` }, { role: 'user', content }], { task: 'applicationImport', model, schemaName: 'application_extraction', schema: EXTRACTION_SCHEMA, validate: value => validateExtraction(normalizeExtraction(value)), skipAudit: true, workspaceId }); const extraction = result.value; const applied_date = resolveAppliedDate(extraction.date_facts, source.sources); const fields = extraction.fields; const duplicates = fields.company.value && fields.position.value ? await getPostgresSql().unsafe('SELECT id,company,position,location FROM applications WHERE workspace_id=$1 AND lower(company)=lower($2) AND lower(position)=lower($3) LIMIT 10', [workspaceId, fields.company.value, fields.position.value]) : []; const analysis: ImportAnalysis = { extraction, applied_date, duplicates: duplicates as ImportAnalysis['duplicates'], model: result.completion.model, prompt_version: `1-${createHash('sha256').update(prompt).digest('hex').slice(0, 12)}` }; await getPostgresSql().unsafe('UPDATE application_imports SET analysis_json=$3 WHERE workspace_id=$1 AND id=$2 AND application_id IS NULL', [workspaceId, source.id, JSON.stringify(analysis)]); res.json(await draft(workspaceId, source.id)) } catch (error) { next(error) } })
cloudApplicationImportsRouter.delete('/:id', async (req, res, next) => { try { const workspaceId = requireWorkspaceId(req); const rows = await getPostgresSql().unsafe('SELECT stored_name,inference_stored_name FROM application_materials WHERE workspace_id=$1 AND import_id=$2', [workspaceId, req.params.id]) as Array<{ stored_name: string | null; inference_stored_name: string | null }>; await getPostgresSql().unsafe('DELETE FROM application_imports WHERE workspace_id=$1 AND id=$2 AND application_id IS NULL', [workspaceId, req.params.id]); rows.flatMap(row => [row.stored_name, row.inference_stored_name]).filter((name): name is string => !!name).forEach(name => { try { unlinkSync(materialPath(workspaceId, name)) } catch {} }); res.json({ ok: true }) } catch (error) { next(error) } })
cloudApplicationImportsRouter.use((error: Error, _req: Request, res: Response, _next: unknown) => { const err = error instanceof CloudImportError ? error : error instanceof AiError ? new CloudImportError(error.message, error.statusCode) : new CloudImportError('材料处理失败，请重试', 500); if (!res.headersSent) res.status(err.status).json({ message: err.message }) })
